// Copyright © 2024 Galactica Network
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: galactica/merkle/query.proto

package indexer

import (
	"reflect"
	"sync"

	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryProofRequest is the request type for the Query.Proof method.
type QueryProofRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// registry  is the ZkCertificateRegistry hex address, which starts with 0x.
	Registry string `protobuf:"bytes,1,opt,name=registry,proto3" json:"registry,omitempty"`
	// leaf is the leaf uint256 value.
	Leaf string `protobuf:"bytes,2,opt,name=leaf,proto3" json:"leaf,omitempty"`
}

func (x *QueryProofRequest) Reset() {
	*x = QueryProofRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_galactica_merkle_query_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryProofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryProofRequest) ProtoMessage() {}

func (x *QueryProofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_galactica_merkle_query_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryProofRequest.ProtoReflect.Descriptor instead.
func (*QueryProofRequest) Descriptor() ([]byte, []int) {
	return file_galactica_merkle_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryProofRequest) GetRegistry() string {
	if x != nil {
		return x.Registry
	}
	return ""
}

func (x *QueryProofRequest) GetLeaf() string {
	if x != nil {
		return x.Leaf
	}
	return ""
}

// QueryProofResponse is the response type for the Query.Proof method.
type QueryProofResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// proof is the merkle proof.
	Proof *Proof `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`
}

func (x *QueryProofResponse) Reset() {
	*x = QueryProofResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_galactica_merkle_query_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryProofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryProofResponse) ProtoMessage() {}

func (x *QueryProofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_galactica_merkle_query_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryProofResponse.ProtoReflect.Descriptor instead.
func (*QueryProofResponse) Descriptor() ([]byte, []int) {
	return file_galactica_merkle_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryProofResponse) GetProof() *Proof {
	if x != nil {
		return x.Proof
	}
	return nil
}

// GetEmptyIndexRequest is the request type for the Query.GetEmptyIndex method.
type GetEmptyIndexRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// registry is the ZkCertificateRegistry hex address, which starts with 0x.
	Registry string `protobuf:"bytes,1,opt,name=registry,proto3" json:"registry,omitempty"`
}

func (x *GetEmptyIndexRequest) Reset() {
	*x = GetEmptyIndexRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_galactica_merkle_query_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEmptyIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmptyIndexRequest) ProtoMessage() {}

func (x *GetEmptyIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_galactica_merkle_query_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmptyIndexRequest.ProtoReflect.Descriptor instead.
func (*GetEmptyIndexRequest) Descriptor() ([]byte, []int) {
	return file_galactica_merkle_query_proto_rawDescGZIP(), []int{2}
}

func (x *GetEmptyIndexRequest) GetRegistry() string {
	if x != nil {
		return x.Registry
	}
	return ""
}

// GetEmptyIndexResponse is the response type for the Query.GetEmptyIndex method.
type GetEmptyIndexResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// index is the empty leaf index.
	Index uint32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *GetEmptyIndexResponse) Reset() {
	*x = GetEmptyIndexResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_galactica_merkle_query_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEmptyIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmptyIndexResponse) ProtoMessage() {}

func (x *GetEmptyIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_galactica_merkle_query_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmptyIndexResponse.ProtoReflect.Descriptor instead.
func (*GetEmptyIndexResponse) Descriptor() ([]byte, []int) {
	return file_galactica_merkle_query_proto_rawDescGZIP(), []int{3}
}

func (x *GetEmptyIndexResponse) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// Proof is the merkle proof.
type Proof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// leaf is the leaf value encoded as a string containing the uint256 value.
	Leaf string `protobuf:"bytes,1,opt,name=leaf,proto3" json:"leaf,omitempty"`
	// path is the merkle proof path, encoded as a string containing the uint256 values.
	Path []string `protobuf:"bytes,2,rep,name=path,proto3" json:"path,omitempty"`
	// index is the leaf index.
	Index uint32 `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	// root is the merkle root, value encoded as a string containing the uint256 value.
	Root string `protobuf:"bytes,4,opt,name=root,proto3" json:"root,omitempty"`
}

func (x *Proof) Reset() {
	*x = Proof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_galactica_merkle_query_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Proof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proof) ProtoMessage() {}

func (x *Proof) ProtoReflect() protoreflect.Message {
	mi := &file_galactica_merkle_query_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proof.ProtoReflect.Descriptor instead.
func (*Proof) Descriptor() ([]byte, []int) {
	return file_galactica_merkle_query_proto_rawDescGZIP(), []int{4}
}

func (x *Proof) GetLeaf() string {
	if x != nil {
		return x.Leaf
	}
	return ""
}

func (x *Proof) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *Proof) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Proof) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

var File_galactica_merkle_query_proto protoreflect.FileDescriptor

var file_galactica_merkle_query_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x67, 0x61, 0x6c, 0x61, 0x63, 0x74, 0x69, 0x63, 0x61, 0x2f, 0x6d, 0x65, 0x72, 0x6b,
	0x6c, 0x65, 0x2f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10,
	0x67, 0x61, 0x6c, 0x61, 0x63, 0x74, 0x69, 0x63, 0x61, 0x2e, 0x6d, 0x65, 0x72, 0x6b, 0x6c, 0x65,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x43,
	0x0a, 0x11, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x6c, 0x65, 0x61, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c,
	0x65, 0x61, 0x66, 0x22, 0x43, 0x0a, 0x12, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x6f,
	0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x70, 0x72, 0x6f,
	0x6f, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x63,
	0x74, 0x69, 0x63, 0x61, 0x2e, 0x6d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x6f,
	0x66, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x22, 0x32, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x22, 0x2d, 0x0a, 0x15,
	0x47, 0x65, 0x74, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x59, 0x0a, 0x05, 0x50,
	0x72, 0x6f, 0x6f, 0x66, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x65, 0x61, 0x66, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6c, 0x65, 0x61, 0x66, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x32, 0xaa, 0x02, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x12, 0x88, 0x01, 0x0a, 0x05, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x23, 0x2e, 0x67, 0x61, 0x6c,
	0x61, 0x63, 0x74, 0x69, 0x63, 0x61, 0x2e, 0x6d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x2e, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x24, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x63, 0x74, 0x69, 0x63, 0x61, 0x2e, 0x6d, 0x65, 0x72, 0x6b,
	0x6c, 0x65, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x34, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x2e, 0x12, 0x2c, 0x2f,
	0x76, 0x31, 0x2f, 0x67, 0x61, 0x6c, 0x61, 0x63, 0x74, 0x69, 0x63, 0x61, 0x2f, 0x6d, 0x65, 0x72,
	0x6b, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x2f, 0x7b, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x79, 0x7d, 0x2f, 0x7b, 0x6c, 0x65, 0x61, 0x66, 0x7d, 0x12, 0x95, 0x01, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x26, 0x2e,
	0x67, 0x61, 0x6c, 0x61, 0x63, 0x74, 0x69, 0x63, 0x61, 0x2e, 0x6d, 0x65, 0x72, 0x6b, 0x6c, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x63, 0x74, 0x69, 0x63,
	0x61, 0x2e, 0x6d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x33,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x2d, 0x12, 0x2b, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x61, 0x6c, 0x61,
	0x63, 0x74, 0x69, 0x63, 0x61, 0x2f, 0x6d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x2f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2f, 0x7b, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x79, 0x7d, 0x42, 0xca, 0x01, 0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x61, 0x6c, 0x61,
	0x63, 0x74, 0x69, 0x63, 0x61, 0x2e, 0x6d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x42, 0x0a, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x45, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x47, 0x61, 0x6c, 0x61, 0x63, 0x74, 0x69, 0x63, 0x61,
	0x2d, 0x63, 0x6f, 0x72, 0x70, 0x2f, 0x6d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x2d, 0x70, 0x72, 0x6f,
	0x6f, 0x66, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x67, 0x61, 0x6c, 0x61, 0x63, 0x74, 0x69, 0x63, 0x61, 0x2f, 0x6d, 0x65, 0x72, 0x6b, 0x6c,
	0x65, 0xa2, 0x02, 0x03, 0x47, 0x4d, 0x58, 0xaa, 0x02, 0x10, 0x47, 0x61, 0x6c, 0x61, 0x63, 0x74,
	0x69, 0x63, 0x61, 0x2e, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0xca, 0x02, 0x10, 0x47, 0x61, 0x6c,
	0x61, 0x63, 0x74, 0x69, 0x63, 0x61, 0x5c, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0xe2, 0x02, 0x1c,
	0x47, 0x61, 0x6c, 0x61, 0x63, 0x74, 0x69, 0x63, 0x61, 0x5c, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65,
	0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x11, 0x47,
	0x61, 0x6c, 0x61, 0x63, 0x74, 0x69, 0x63, 0x61, 0x3a, 0x3a, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_galactica_merkle_query_proto_rawDescOnce sync.Once
	file_galactica_merkle_query_proto_rawDescData = file_galactica_merkle_query_proto_rawDesc
)

func file_galactica_merkle_query_proto_rawDescGZIP() []byte {
	file_galactica_merkle_query_proto_rawDescOnce.Do(func() {
		file_galactica_merkle_query_proto_rawDescData = protoimpl.X.CompressGZIP(file_galactica_merkle_query_proto_rawDescData)
	})
	return file_galactica_merkle_query_proto_rawDescData
}

var file_galactica_merkle_query_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_galactica_merkle_query_proto_goTypes = []interface{}{
	(*QueryProofRequest)(nil),     // 0: galactica.merkle.QueryProofRequest
	(*QueryProofResponse)(nil),    // 1: galactica.merkle.QueryProofResponse
	(*GetEmptyIndexRequest)(nil),  // 2: galactica.merkle.GetEmptyIndexRequest
	(*GetEmptyIndexResponse)(nil), // 3: galactica.merkle.GetEmptyIndexResponse
	(*Proof)(nil),                 // 4: galactica.merkle.Proof
}
var file_galactica_merkle_query_proto_depIdxs = []int32{
	4, // 0: galactica.merkle.QueryProofResponse.proof:type_name -> galactica.merkle.Proof
	0, // 1: galactica.merkle.Query.Proof:input_type -> galactica.merkle.QueryProofRequest
	2, // 2: galactica.merkle.Query.GetEmptyIndex:input_type -> galactica.merkle.GetEmptyIndexRequest
	1, // 3: galactica.merkle.Query.Proof:output_type -> galactica.merkle.QueryProofResponse
	3, // 4: galactica.merkle.Query.GetEmptyIndex:output_type -> galactica.merkle.GetEmptyIndexResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_galactica_merkle_query_proto_init() }
func file_galactica_merkle_query_proto_init() {
	if File_galactica_merkle_query_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_galactica_merkle_query_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryProofRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_galactica_merkle_query_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryProofResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_galactica_merkle_query_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEmptyIndexRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_galactica_merkle_query_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEmptyIndexResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_galactica_merkle_query_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Proof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_galactica_merkle_query_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_galactica_merkle_query_proto_goTypes,
		DependencyIndexes: file_galactica_merkle_query_proto_depIdxs,
		MessageInfos:      file_galactica_merkle_query_proto_msgTypes,
	}.Build()
	File_galactica_merkle_query_proto = out.File
	file_galactica_merkle_query_proto_rawDesc = nil
	file_galactica_merkle_query_proto_goTypes = nil
	file_galactica_merkle_query_proto_depIdxs = nil
}
